module RSpec
  module Given
    VERSION_MAJOR = 1
    VERSION_MINOR = 2
    VERSION_BUILD = 0
    VERSION_NUMBERS = [VERSION_MAJOR, VERSION_MINOR, VERSION_BUILD]
    VERSION = VERSION_NUMBERS.join(".")
  end
end
